server:
  port: 8090

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
    #url: ${DB_URL:jdbc:postgresql://localhost:5432/}
    #platform: postgres
    #username: ${DB_USER:postgres}
    #password: ${DB_PWD:postgres}
    url: jdbc:h2:mem:donus
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        #show_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace